version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./tools/docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/application
    container_name: webpack-hmr-docker_app
